# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8575678da1ed7631faba21f1d573321784236f12411e50d5124cd57c9fee1f87f95da03ab267c7e22ddd9169ed7aeb2c9e4098d447df361b4dac18e1f622293d

test:
  secret_key_base: de9b7314c621c7b5449d11941c988ebac37bd5e8e11ff1837e01147731d4fc85a6384f7a272c97338c7e34f83c7a4f40c87725d7f1013dec50d2defe070f2de4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
